model: preact_resnet34
batch_size: 512
lr: 0.1
weight_decay: 2e-5
epochs: 100
calib_epochs: 10
clip_grad_norm: 1.0
data_type: imagenet
data_path: ~/datasets/imagenet
auto_aug: False
cutout: False
output_dir: ./logs/noisy
print_freq: 256

use_noise: True
noise_type: gaussian
noise_prob: 0.5
init_T: 8
min_T: 1
max_T: 16
scale: 1.0
penalty: 1e-2