model: vggsnn_cifar
batch_size: 128
lr: 0.1
weight_decay: 5e-4
epochs: 300
calib_epochs: 10
clip_grad_norm: 1.0
data_type: cifar100
data_path: ~/datasets/cifar100
output_dir: ./logs/noisy
print_freq: 256

use_noise: True
noise_type: gaussian
noise_prob: 0.5
init_T: 8
min_T: 1
max_T: 16
scale: 1.0
penalty: 1e-2